@domain = http://localhost:3000

### Users Index
GET {{ domain }}/users


### Users Create (signup)
POST {{ domain }}/users.json
Content-Type: application/json

{
  "email": "test@test.com",
  "user_name": "test user",
  "password": "password",
  "password_confirmation": "password",
  "is_business": false
}

### Users Show
GET {{ domain }}/users/13

### Users Update
PATCH {{ domain }}/users/13
Content-Type: application/json

{
  "is_business": false
}

### Users Delete
DELETE {{ domain }}/users/12

### Sessions create (login)
POST {{ domain }}/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Airports Index
GET {{ domain }}/airports

### Airports Create
POST {{ domain }}/airports
Content-Type: application/json

{
  "name": "Test Airport",
  "code": "TST",
  "zip_code": "12345",
  "city": "Happy Land",
  "address": "123 Happy Street"
}

### Airports Show
GET {{ domain }}/airports/1

### Airports Update
PATCH {{ domain }}/airports/3
Content-Type: application/json

{
  "zip_code": "94128"
}

### Airports Delete

DELETE {{ domain }}/airports/5